version: '3.9'

services:
  data-api:
    build: .
    ports:
      - 80:3000
    restart: unless-stopped
    environment: 
      PORT:            3000
      POSTGRESQL_URL:  ${POSTGRESQL_URL:?POSTGRESQL_URL is missing}
      INFLUXDB_URL:    ${INFLUXDB_URL:?INFLUXDB_URL is missing}
      INFLUXDB_TOKEN:  ${INFLUXDB_TOKEN:?INFLUXDB_TOKEN is missing}
      INFLUXDB_BUCKET: ${INFLUXDB_BUCKET:?INFLUXDB_BUCKET is missing}
      INFLUXDB_ORG:    ${INFLUXDB_ORG:?INFLUXDB_ORG is missing}
      RABBITMQ_URL:    ${RABBITMQ_URL:?RABBITMQ_URL is missing}
